-- nova.require "trial_purgatory"
nova.require "aotr.lua"
nova.require "aort.lua"
nova.require "aoa.lua"
nova.require "aoch.lua"
nova.require "aonr.lua"
nova.require "aoda.lua"
nova.require "aobr.lua"
nova.require "aovo.lua"
-- nova.require "aoin.lua"
-- nova.require "aode.lua"
-- nova.require "aohe.lua"
nova.require "aoca.lua"
-- nova.require "aomo.lua"
nova.require "aohua.lua"
-- nova.require "aohu.lua"
