nova.require "mods/JH_mega_challenges_pack/trial_tourism"
-- nova.require "mods/JH_mega_challenges_pack/aonu.lua"
nova.require "mods/JH_mega_challenges_pack/aort.lua"
nova.require "mods/JH_mega_challenges_pack/aobr.lua"
nova.require "mods/JH_mega_challenges_pack/aoda.lua"
nova.require "mods/JH_mega_challenges_pack/aovo.lua"
nova.require "mods/JH_mega_challenges_pack/aoin.lua"
nova.require "mods/JH_mega_challenges_pack/aode.lua"
nova.require "mods/JH_mega_challenges_pack/aoca.lua"
nova.require "mods/JH_mega_challenges_pack/aomo.lua"
nova.require "mods/JH_mega_challenges_pack/aohu.lua"
