-- nova.require "mods/mega_challenge_pack/trial_purgatory"
nova.require "mods/mega_challenge_pack/aotr.lua"
nova.require "mods/mega_challenge_pack/aort.lua"
nova.require "mods/mega_challenge_pack/aoa.lua"
nova.require "mods/mega_challenge_pack/aoch.lua"
nova.require "mods/mega_challenge_pack/aonr.lua"
nova.require "mods/mega_challenge_pack/aoda.lua"
nova.require "mods/mega_challenge_pack/aobr.lua"
nova.require "mods/mega_challenge_pack/aovo.lua"
-- nova.require "mods/mega_challenge_pack/aoin.lua"
-- nova.require "mods/mega_challenge_pack/aode.lua"
nova.require "mods/mega_challenge_pack/aohe.lua"
nova.require "mods/mega_challenge_pack/aoca.lua"
-- nova.require "mods/mega_challenge_pack/aomo.lua"
nova.require "mods/mega_challenge_pack/aohua.lua"
-- nova.require "mods/JH_mega_challenge_pack/aohu.lua"
